#!/bin/sh
set -euo pipefail

LANGUAGE=$1
PROBLEM=$2
ROOT=$(pwd)

alias diff="diff -y --color"

cd $ROOT/$LANGUAGE

if [ -f "prepare" ]; then
  ./prepare $PROBLEM
fi

cd $ROOT

$ROOT/utils/populate_tests $PROBLEM

cd $ROOT/$LANGUAGE

echo "Validating $LANGUAGE:$PROBLEM"

INPUTS=$(ls "$ROOT/tests/$PROBLEM" | grep "\.in$" | sed "s/\.in$//")

input_index=0
input_length=$(echo $INPUTS | wc -w)
failed=false
for input_name in $INPUTS
do
  input_index=$((input_index+1))
  echo -n "Test $input_index/$input_length.."
  INPUT=$(cat "$ROOT/tests/$PROBLEM/$input_name.in")
  OUTPUT=$(echo $INPUT | $ROOT/$LANGUAGE/run $PROBLEM)
  EXPECTED=$(cat "$ROOT/tests/$PROBLEM/$input_name.ans")

  res=0
  DIFF=$(diff <(echo $EXPECTED) <(echo $OUTPUT)) || res=$?

  if [ $res == 0 ]; then
    echo "PASS"
  else
    echo "FAIL"
    echo $DIFF
    failed=true
  fi
done

if [ $failed = false ]; then
  $ROOT/submit -p $PROBLEM -l $LANGUAGE -f $($ROOT/$LANGUAGE/source $PROBLEM)
fi
